baseURL = "https://roman403.github.io/ProyectoAlpha-Final/"
languageCode = "es"
theme = "tale"

[menu]
  [[menu.main]]
    identifier = "DNS"
    name = "DNS"
    title = "DNS"
    url = "/posts/dns"
    weight = 0
  [[menu.main]]
    identifier = "PAGINA WEB VISUAL"
    name = "PAGINA WEB VISUAL"
    title = "PAGINA WEB VISUAL"
    url = "/posts/PaginaWebVisual"
    weight = 0
  [[menu.main]]
    identifier = "CORREO"
    name = "CORREO"
    title = "CORREO"
    url = "/posts/CORREO"
    weight = 0
  [[menu.main]]
    identifier = "HUGO"
    name = "HUGO"
    title = "HUGO"
    url = "/posts/HUGO"
    weight = 0
  [[menu.main]]
    identifier = "BACKUP"
    name = "BACKUP"
    title = "BACKUP"
    url = "/posts/BACKUP"
    weight = 0
  [[menu.main]]
    identifier = "SEGURIDAD"
    name = "SEGURIDAD"
    title = "SEGURIDAD"
    url = "/posts/SEGURIDAD"
    weight = 0
  [[menu.main]]
    identifier = "PAGINA WEB"
    name = "PAGINA WEB"
    title = "PAGINA WEB"
    url = "/posts/SERVICIOS"
    weight = 0
  [[menu.main]]
    identifier = "VPN"
    name = "VPN"
    title = "VPN"
    url = "/posts/VPN"
    weight = 0
    [[menu.main]]
    identifier = "WORDPRESS"
    name = "WORDPRESS"
    title = "WORDPRESS"
    url = "/posts/WORDPRESS"
    weight = 0
  [[menu.main]]
    identifier = "ARQUITECTURA"
    name = "ARQUITECTURA"
    title = "ARQUITECTURA"
    url = "/ARQUITECTURA/"
    weight = 0