baseURL = "https://github.com/roman403/ProyectoAlpha-Final/"
languageCode = "es"
title = "ALPHA"
theme = "tale"

[menu]
  [[menu.main]]
    identifier = "arquitectura"
    name = "arquitectura"
    title = "arquitectura"
    url = "/arquitectura/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0