baseURL = "https://roman403.github.io/ProyectoAlpha-Final/"
languageCode = "es"
title = "ALPHA"
theme = "tale"

[menu]
  [[menu.main]]
    identifier = "arquitectura"
    name = "arquitectura"
    title = "arquitectura"
    url = "/arquitectura/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0
  [[menu.main]]
    identifier = "DNS"
    name = "DNS"
    title = "DNS"
    url = "/posts/dns"
    weight = 0
  [[menu.main]]
    identifier = "HUGO"
    name = "HUGO"
    title = "HUGO"
    url = "/posts/HUGO"
    weight = 0
   [[menu.main]]
    identifier = "BACKUP"
    name = "BACKUP"
    title = "BACKUP"
    url = "/posts/BACKUP"
    weight = 0
   [[menu.main]]
    identifier = "NGINX"
    name = "NGINX"
    title = "NGINX"
    url = "/posts/NGINX"
    weight = 0